<a href="https://colab.research.google.com/github/rodolfo-flores-tierconnect-com/training/blob/main/DataEngineer_TechnicalTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python


## Exercise 1. 
Generate a funcion to check if a string is palindrome or not.

Example of palindrome word: "Solos"

In [ ]:
# Add your function here

def is_palindrome():
  return

In [ ]:
# Test and validate your results

# SQL

In [ ]:
!pip install pandasql

In [ ]:
import pandas as pd
df = pd.read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

In [ ]:
sqldf("select * from df limit 10")

  iso_code continent  ... life_expectancy human_development_index
0      AFG      Asia  ...           64.83                   0.498
1      AFG      Asia  ...           64.83                   0.498
2      AFG      Asia  ...           64.83                   0.498
3      AFG      Asia  ...           64.83                   0.498
4      AFG      Asia  ...           64.83                   0.498
5      AFG      Asia  ...           64.83                   0.498
6      AFG      Asia  ...           64.83                   0.498
7      AFG      Asia  ...           64.83                   0.498
8      AFG      Asia  ...           64.83                   0.498
9      AFG      Asia  ...           64.83                   0.498

[10 rows x 55 columns]

## Exercise 1
Retrieve the number of deaths in Bolivia

In [ ]:
sqldf("select ......")

# Pandas

## Exercise 1
Using pandas
Retrieve from df dataframe the number of cases and deaths in South America Countries.  (Hint: Use groupby by continent and location)

In [ ]:
# Add your solution here
# df[df[]].groupby()....

                         new_cases  new_deaths
continent     location
South America Argentina  1770715.0     45125.0
              Bolivia     181016.0      9530.0
              Brazil     8324294.0    207095.0
              Chile       656712.0     17294.0
              Colombia   1849101.0     47491.0
              Ecuador     226002.0     14246.0
              Guyana        6745.0       170.0
              Paraguay    119640.0      2466.0
              Peru       1040231.0     38399.0
              Suriname      7300.0       139.0
              Uruguay      29989.0       280.0
              Venezuela   118415.0      1090.0